### ISSUE TITLE
Front page: add thousands separators

### ISSUE THREAD

**Issue by hugovk** [City-of-Helsinki/digihel#124]
This:
![image](https://cloud.githubusercontent.com/assets/1324225/26373415/26d71fbe-400a-11e7-8469-f1315480a890.png)

Should look like this:
![image](https://cloud.githubusercontent.com/assets/1324225/26373461/50c223d2-400a-11e7-950a-5c744b190faf.png)

So the numbers are more readable and to follow convention.

Change is needed here: https://github.com/City-of-Helsinki/digihel/blob/17e4b1e962b5aabfb5009f1e7497cea6fd673ac5/digi/templates/digi/front_page.html#L24

**Comment by terotic** [comment]
Fixed in a3c86f0548e84807439a1bcac77ad9098a1b24fa
