### ISSUE TITLE
Some TinyMCE content formatting is removed on publish

### ISSUE THREAD

**Issue by terotic** [City-of-Helsinki/digihel#61]
To reproduce:

1. Create a table with text content inside on TinyMCE editor
2. Publish
3. Check published page html / formatting

**Comment by terotic** [comment]
`<code></code>` formatting also gets cleaned.

**Comment by terotic** [comment]
anchor tag id is also removed. issue #38 ?

**Comment by akx** [comment]
Okie, I'll add those too.

**Comment by akx** [comment]
@terotic Code and Pre is now explicitly allowed, and `a` elements go through unsanitized.
